### ISSUE TITLE
Support for tables

### ISSUE THREAD

**Issue by guitarflow** [amiremohamadi/DuckX#26]
First of all thanks so much for creating this library!
Very clean and easy to use interface with few dependencies - great!
I tried libopc and while it seems to be very comprehensive, it has a ton of dependencies which makes it rather hard to add to a real app. 

I'm about to start a new project which requires parsing docx (among others).
I thought there would be several libraries for reading docx files with C++ but had to find out there are actually not many.

The documents I need to parse typically contain tables and while using the DuckX sample code I'm ending up with almost no output. Do you think it's possible to add support for tables in the near future?

Thanks and keep up the great work!

**Comment by amiremohamadi** [comment]
Thank you @guitarflow.
Nice suggestion! It would be a great feature.
But **Duckx** is under development and I'm trying to add many common features, so it may take time to add some suggestions. 
Any contributions are welcomed! :smiley:

**Comment by lmJack** [comment]
I want to write a docx file,but from the sample i can't make it ,how should i do?can you give me  some example  to write a docx file?
