### ISSUE TITLE
Save function doesn't work correctly

### ISSUE THREAD

**Issue by amiremohamadi** [amiremohamadi/DuckX#29]
**Describe the bug**
When you modify the word document and save it, the old `document.xml` must be replaced.
But currently It adds a file with the same name to the word document.

**Example**
In this case, after calling save function we have two `document.xml`:
Archive:  my_test.docx
  Length      Date    Time    Name
---------  ---------- -----   ----
      573  02-03-2019 17:16   _rels/.rels
      513  02-03-2019 17:16   docProps/app.xml
      732  02-03-2019 17:16   docProps/core.xml
      531  02-03-2019 17:16   word/_rels/document.xml.rels
      280  02-03-2019 17:16   word/settings.xml
      853  02-03-2019 17:16   word/fontTable.xml
     1480  02-03-2019 17:16   word/document.xml
     2585  02-03-2019 17:16   word/styles.xml
     1118  02-03-2019 17:16   [Content_Types].xml
     1602  07-03-2019 23:14   word/document.xml
---------                     -------
    10267                     10 files

**Expected behavior**
Remove the old `document.xml` and replace it with the new one.

**Additional context**
This may be due to the zip library.

**Comment by TouchTheFish** [comment]
yes，This library is not useful at all. You can't save it.
