### ISSUE TITLE
Chinese document shows chaos

### ISSUE THREAD

**Issue by christopherwoo** [amiremohamadi/DuckX#54]
I test **sample1.cpp**, it works fine. 

While I change the code by giving it a _Chinese docx file_, the output can not be read.
Seems to be concerned with **character encoding**.

Help!

**Comment by amiremohamadi** [comment]
Hi @christopherwoo! thanks for reporting.

Unfortunately Duckx only supports ASCII characters yet.
I don't have time to work on it so feel free to open a PR.

by the way thank you for reporting.
